### PR TITLE
Internationalize text & code improvements

### PR DESCRIPTION
**Pull request by grappler**
Hello, after reading the article on WP Tavern I checked out the GItHub repo and saw some things that I could improve.
- Internationalized the text, loaded the text domain and created a POT file for the translators
- Made sure all of the functions are prefixed correctly with `hello_security` so that there are no conflicts
- Changed `hello_security()` to `hello_security_echo_quote` so that it is clear what the function does
- Changed the variable `$x` to `$direction` so that it is clear what the variable is.

### CODE REVIEW

**Comment by grappler** [comment]
@mlbanddrb Did you see my pull request?

**Comment by mlbanddrb** [comment]
Hey Grappler! Thank you for sending the second message because I did not see the one from May. I will definitely update this and give you credit. As this was my first plugin, while an easy one, I was still on a learning curve.

**Comment by mlbanddrb** [comment]
Hey grappler,

I have a WordCamp this weekend so I might not be able to push the update until next week but I will definitely be doing it soon. Thank you again!

**Comment by grappler** [comment]
Enjoy your WordCamp. Let me know if you have any questions to the code :smile:

**Pull request merged**
